### ISSUE TITLE
Read/Solves shows `Summit Read/Solves'

### ISSUE THREAD

**Issue by hsprakash** [GavHern/better-slp#23]
When you click {progress, year, week, or announcements} then college or resource it shows up as _**Summit Reads/Solves**_

![image](https://user-images.githubusercontent.com/24233112/215021376-b1d332db-d34c-4e61-a64d-f90b6dbf9c4b.png)
 @GavHern

**Comment by heather-loll** [comment]
Duplicate of #21 but important enough that ill leave this open since its a really bad bug lol

**Comment by heather-loll** [comment]
nevermind, gonna close since its the same bug as #21
